[package]
name = "minimum-rust-template"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = "abort"

[profile.release.package."*"]
opt-level = 3
strip = true
codegen-units = 1

[dependencies]
