[unstable]
build-std = ["std", "core", "alloc", "proc_macro"]
build-std-features = ["panic-unwind"]
unstable-options = true

[build]
artifact-dir = "build"

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clink-arg=/MERGE:.rdata=.text", "-Clink-arg=/MERGE:.pdata=.text", "-Clink-arg=/MERGE:_RDATA=.text", "-Clink-arg=/EMITPOGOPHASEINFO", "-Clink-arg=/DEBUG:NONE"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.x86_64-pc-windows-gnullvm]
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.x86_64-apple-darwin]
rustflags = ["-Ctarget-cpu=x86-64-v3", "-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-Clink-arg=/MERGE:.rdata=.text", "-Clink-arg=/MERGE:.pdata=.text", "-Clink-arg=/MERGE:_RDATA=.text", "-Clink-arg=/EMITPOGOPHASEINFO", "-Clink-arg=/DEBUG:NONE"]

[target.aarch64-pc-windows-gnullvm]
rustflags = ["-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]

[target.aarch64-apple-darwin]
rustflags = ["-Clink-args=-Wl,-no-pie,-build-id=none,--no-eh-frame-hdr,--gc-sections,-s"]